name: CI

on:
  push:
  pull_request:

jobs:
  linux-ci:
    name: Linux
    runs-on: ubuntu-latest
    container: node:lts
    services:
      minio:
        image: minio/minio:edge-cicd
        env:
          MINIO_ROOT_USER: teknologi-umum
          MINIO_ROOT_PASSWORD: very-strong-password
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl -f http://minio:9000/minio/health/live"
          --health-interval 45s
          --health-timeout 30s
          --health-retries 10
          --health-start-period 120s
        volumes:
          - minio-data:/data
      gcs:
        image: fsouza/fake-gcs-server
        ports:
          - 4443:4443
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump npm version
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx eslint --ignore-path .gitignore --ext .js,.ts .

      - name: Build
        run: npm run build

      - name: Prepare temporary directory
        run: |
          mkdir -p ${{ runner.temp }}
          chown -R $(whoami):$(whoami) ${{ runner.temp }}

      - name: Test
        run: npx vitest run --coverage
        env:
          TEMP_DIR: ${{ runner.temp }}
          S3_HOST: http://minio:9000
          S3_ACCESS: teknologi-umum
          S3_SECRET: very-strong-password

      - name: Send coverage report to Codecov
        uses: codecov/codecov-action@v3
