name: CI

on:
  push:
  pull_request:

jobs:
  linux-ci:
    name: Linux
    runs-on: ubuntu-latest
    container: node:lts
    services:
      minio:
        image: minio/minio:edge-cicd
        env:
          MINIO_ROOT_USER: teknologi-umum
          MINIO_ROOT_PASSWORD: very-strong-password
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl -f http://minio:9000/minio/health/live"
          --health-interval 45s
          --health-timeout 30s
          --health-retries 10
          --health-start-period 120s
        volumes:
          - minio-data:/data
      gcs:
        image: fsouza/fake-gcs-server
        ports:
          - 4443:4443
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Bump npm version
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx eslint --ignore-path .gitignore .

      - name: Build
        run: npm run build

      - name: Test
        run: npx vitest run --coverage
        env:
          TEMP_DIR: ${{ runner.temp }}

      - name: Send coverage report to Codecov
        uses: codecov/codecov-action@v3
