name: Secret Scan

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  trufflehog:
    name: Trufflehog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --debug --only-verified